package com.example.ui.components

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Clear
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.Face
import androidx.compose.material.icons.filled.GraphicEq
import androidx.compose.material.icons.filled.Movie
import androidx.compose.material.icons.filled.Pause
import androidx.compose.material.icons.filled.Person
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material.icons.filled.RecordVoiceOver
import androidx.compose.material.icons.filled.Save
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.Speed
import androidx.compose.material.icons.filled.Stop
import androidx.compose.material.icons.filled.Tune
import androidx.compose.material.icons.filled.Videocam
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.audio.LocalizedDubbingCue
import com.example.audio.VideoDubbingSynthesisAnalysis
import com.example.ui.LocalizedDubbingCuesUiState
import java.util.Locale

/**
 * Modern Jetpack Compose UI component displaying the list of `LocalizedDubbingCue`
 * generated by the Gemini Automatic Video-to-Audio Dubbing Synthesis Service.
 *
 * Provides granular audio playback for every individual scene segment with pitch/rate adaptation,
 * live animated waveform indicators, character badge styling, script editing, and studio integration.
 */
@OptIn(ExperimentalLayoutApi::class)
@Composable
fun LocalizedDubbingCuesComponent(
    uiState: LocalizedDubbingCuesUiState,
    onPlayCue: (LocalizedDubbingCue) -> Unit,
    onStopAudio: () -> Unit,
    onPlayAll: () -> Unit,
    onSynthesizeCue: (LocalizedDubbingCue) -> Unit,
    onUpdateScript: (cueId: String, newScript: String) -> Unit,
    onApplyToStudio: (LocalizedDubbingCue) -> Unit,
    onFilterGender: (String?) -> Unit,
    onSearchQueryChange: (String) -> Unit,
    onReloadSamples: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var editingCue by remember { mutableStateOf<LocalizedDubbingCue?>(null) }

    // Dialog for editing script inline
    if (editingCue != null) {
        val targetCue = editingCue!!
        var editedScriptText by remember(targetCue) { mutableStateOf(targetCue.localizedDubbedScript) }

        AlertDialog(
            onDismissRequest = { editingCue = null },
            title = {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Edit,
                        contentDescription = null,
                        tint = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = "تعديل نص الدبلجة للمقطع",
                        fontWeight = FontWeight.Bold,
                        fontSize = 16.sp
                    )
                }
            },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    Text(
                        text = "الشخصية: ${targetCue.characterSpeakerName} (${targetCue.characterGender})",
                        fontSize = 12.sp,
                        color = MaterialTheme.colorScheme.primary,
                        fontWeight = FontWeight.SemiBold
                    )
                    Text(
                        text = "التوقيت: ${targetCue.formattedTimeRange}",
                        fontSize = 11.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    OutlinedTextField(
                        value = editedScriptText,
                        onValueChange = { editedScriptText = it },
                        label = { Text("النص العربي المدبلج") },
                        minLines = 3,
                        maxLines = 5,
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("edit_cue_script_input")
                    )
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        onUpdateScript(targetCue.id, editedScriptText)
                        editingCue = null
                        Toast.makeText(context, "تم تحديث نص المقطع بنجاح! ✨", Toast.LENGTH_SHORT).show()
                    },
                    modifier = Modifier.testTag("confirm_edit_cue_script_button")
                ) {
                    Text("حفظ التعديل")
                }
            },
            dismissButton = {
                TextButton(onClick = { editingCue = null }) {
                    Text("إلغاء")
                }
            }
        )
    }

    // Filtered Cues
    val filteredCues = remember(uiState.cues, uiState.selectedGenderFilter, uiState.searchQuery) {
        uiState.cues.filter { cue ->
            val matchesGender = uiState.selectedGenderFilter == null ||
                    cue.characterGender.equals(uiState.selectedGenderFilter, ignoreCase = true)
            val matchesSearch = uiState.searchQuery.isBlank() ||
                    cue.localizedDubbedScript.contains(uiState.searchQuery, ignoreCase = true) ||
                    cue.originalDialogue.contains(uiState.searchQuery, ignoreCase = true) ||
                    cue.characterSpeakerName.contains(uiState.searchQuery, ignoreCase = true) ||
                    cue.visualActionDescription.contains(uiState.searchQuery, ignoreCase = true)
            matchesGender && matchesSearch
        }
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(horizontal = 14.dp, vertical = 8.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        // 1. Service Analysis Header Card
        AnalysisOverviewHeaderCard(
            analysis = uiState.analysisResult,
            totalCuesCount = uiState.cues.size,
            isPlayingAll = uiState.isPlayingAll,
            onPlayAll = onPlayAll,
            onStopAudio = onStopAudio,
            onReloadSamples = onReloadSamples
        )

        // 2. Search & Gender Filter Row
        SearchAndFilterBar(
            searchQuery = uiState.searchQuery,
            onSearchQueryChange = onSearchQueryChange,
            selectedGender = uiState.selectedGenderFilter,
            onSelectGender = onFilterGender,
            cuesCount = filteredCues.size
        )

        // 3. Error Banner if any
        AnimatedVisibility(visible = uiState.errorMessage != null) {
            Surface(
                color = Color(0xFFEF4444).copy(alpha = 0.15f),
                shape = RoundedCornerShape(12.dp),
                border = BorderStroke(1.dp, Color(0xFFEF4444).copy(alpha = 0.4f)),
                modifier = Modifier.fillMaxWidth()
            ) {
                Row(
                    modifier = Modifier.padding(12.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(Icons.Default.Clear, contentDescription = null, tint = Color(0xFFEF4444))
                    Text(
                        text = uiState.errorMessage ?: "",
                        color = Color(0xFFEF4444),
                        fontSize = 12.sp,
                        fontWeight = FontWeight.Medium
                    )
                }
            }
        }

        // 4. Loading Indicator or Cues List
        if (uiState.isLoading) {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(260.dp),
                contentAlignment = Alignment.Center
            ) {
                Column(
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    CircularProgressIndicator(color = MaterialTheme.colorScheme.primary)
                    Text(
                        text = "جاري استخراج وتحليل توقيتات الفيديو عبر Gemini Service...",
                        fontSize = 13.sp,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                }
            }
        } else if (filteredCues.isEmpty()) {
            EmptyCuesStateCard(
                hasFilters = uiState.searchQuery.isNotBlank() || uiState.selectedGenderFilter != null,
                onResetFilters = {
                    onSearchQueryChange("")
                    onFilterGender(null)
                },
                onLoadSample = onReloadSamples
            )
        } else {
            // LazyColumn of all LocalizedDubbingCues
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f)
                    .testTag("localized_cues_lazy_column"),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                itemsIndexed(
                    items = filteredCues,
                    key = { _, cue -> cue.id }
                ) { index, cue ->
                    val isPlayingThisCue = uiState.currentlyPlayingCueId == cue.id

                    LocalizedDubbingCueCard(
                        cue = cue,
                        index = index + 1,
                        isPlaying = isPlayingThisCue,
                        onPlay = { onPlayCue(cue) },
                        onStop = onStopAudio,
                        onSynthesize = { onSynthesizeCue(cue) },
                        onEdit = { editingCue = cue },
                        onApplyToStudio = { onApplyToStudio(cue) },
                        onCopyText = {
                            val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                            val clip = ClipData.newPlainText("Dubbing Script", cue.localizedDubbedScript)
                            clipboard.setPrimaryClip(clip)
                            Toast.makeText(context, "تم نسخ النص المدبلج للحافظة! 📋", Toast.LENGTH_SHORT).show()
                        }
                    )
                }
                item {
                    Spacer(Modifier.height(40.dp))
                }
            }
        }
    }
}

/**
 * Top summary overview card with analysis metadata and master Play All controls
 */
@Composable
fun AnalysisOverviewHeaderCard(
    analysis: VideoDubbingSynthesisAnalysis?,
    totalCuesCount: Int,
    isPlayingAll: Boolean,
    onPlayAll: () -> Unit,
    onStopAudio: () -> Unit,
    onReloadSamples: () -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .testTag("analysis_overview_card"),
        shape = RoundedCornerShape(18.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.55f)),
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.6f))
    ) {
        Column(
            modifier = Modifier.padding(14.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Box(
                        modifier = Modifier
                            .size(36.dp)
                            .background(
                                Brush.linearGradient(
                                    listOf(MaterialTheme.colorScheme.primary, Color(0xFF6366F1))
                                ),
                                CircleShape
                            ),
                        contentAlignment = Alignment.Center
                    ) {
                        Icon(
                            imageVector = Icons.Default.AutoAwesome,
                            contentDescription = null,
                            tint = Color.White,
                            modifier = Modifier.size(20.dp)
                        )
                    }
                    Column {
                        Text(
                            text = "توقيتات الدبلجة الذكية (Gemini Cues)",
                            fontSize = 14.sp,
                            fontWeight = FontWeight.Bold
                        )
                        Text(
                            text = analysis?.videoTitleOrSummary ?: "تحليل ومطابقة التوقيتات والمشاهد البصرية",
                            fontSize = 11.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis
                        )
                    }
                }

                Surface(
                    shape = RoundedCornerShape(12.dp),
                    color = MaterialTheme.colorScheme.primary.copy(alpha = 0.15f)
                ) {
                    Text(
                        text = "$totalCuesCount مقاطع",
                        color = MaterialTheme.colorScheme.primary,
                        fontSize = 11.5.sp,
                        fontWeight = FontWeight.Bold,
                        modifier = Modifier.padding(horizontal = 9.dp, vertical = 3.dp)
                    )
                }
            }

            // Tags row: Genre, Dialect, Total Duration
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(6.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                if (analysis != null) {
                    CueMetadataPill(
                        icon = Icons.Default.Movie,
                        text = analysis.detectedSceneGenre,
                        backgroundColor = Color(0xFF8B5CF6).copy(alpha = 0.15f),
                        contentColor = Color(0xFFA78BFA)
                    )
                    CueMetadataPill(
                        icon = Icons.Default.Tune,
                        text = analysis.targetDialectName,
                        backgroundColor = Color(0xFF10B981).copy(alpha = 0.15f),
                        contentColor = Color(0xFF34D399)
                    )
                    CueMetadataPill(
                        icon = Icons.Default.Speed,
                        text = "${String.format(Locale.getDefault(), "%.1f", analysis.totalDurationSeconds)}s",
                        backgroundColor = Color(0xFF3B82F6).copy(alpha = 0.15f),
                        contentColor = Color(0xFF60A5FA)
                    )
                }
            }

            // Actions row: Play All vs Stop & Reload
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Button(
                    onClick = if (isPlayingAll) onStopAudio else onPlayAll,
                    colors = ButtonDefaults.buttonColors(
                        containerColor = if (isPlayingAll) Color(0xFFEF4444) else Color(0xFF10B981)
                    ),
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier
                        .weight(1.3f)
                        .height(42.dp)
                        .testTag("play_all_cues_button")
                ) {
                    Icon(
                        imageVector = if (isPlayingAll) Icons.Default.Stop else Icons.Default.PlayArrow,
                        contentDescription = null,
                        modifier = Modifier.size(18.dp)
                    )
                    Spacer(Modifier.width(6.dp))
                    Text(
                        text = if (isPlayingAll) "إيقاف السرد ⏹️" else "تشغيل السلسلة كاملة ▶",
                        fontWeight = FontWeight.Bold,
                        fontSize = 12.sp
                    )
                }

                OutlinedButton(
                    onClick = onReloadSamples,
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier
                        .weight(0.9f)
                        .height(42.dp)
                        .testTag("reload_sample_cues_button")
                ) {
                    Icon(Icons.Default.AutoAwesome, contentDescription = null, modifier = Modifier.size(15.dp))
                    Spacer(Modifier.width(4.dp))
                    Text("عينات نموذجية", fontSize = 11.5.sp)
                }
            }
        }
    }
}

/**
 * Filter Chips and Search Text Field
 */
@OptIn(ExperimentalLayoutApi::class)
@Composable
fun SearchAndFilterBar(
    searchQuery: String,
    onSearchQueryChange: (String) -> Unit,
    selectedGender: String?,
    onSelectGender: (String?) -> Unit,
    cuesCount: Int
) {
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        // Search text field
        OutlinedTextField(
            value = searchQuery,
            onValueChange = onSearchQueryChange,
            placeholder = { Text("ابحث في النص، الشخصية، أو المشهد...", fontSize = 12.sp) },
            leadingIcon = {
                Icon(Icons.Default.Search, contentDescription = null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(18.dp))
            },
            trailingIcon = {
                if (searchQuery.isNotBlank()) {
                    IconButton(onClick = { onSearchQueryChange("") }, modifier = Modifier.size(24.dp)) {
                        Icon(Icons.Default.Clear, contentDescription = "مسح", modifier = Modifier.size(16.dp))
                    }
                }
            },
            singleLine = true,
            shape = RoundedCornerShape(12.dp),
            modifier = Modifier
                .fillMaxWidth()
                .height(50.dp)
                .testTag("cues_search_textfield")
        )

        // Gender Filter Chips
        FlowRow(
            horizontalArrangement = Arrangement.spacedBy(6.dp),
            verticalArrangement = Arrangement.spacedBy(6.dp)
        ) {
            val filters = listOf(
                Pair(null, "الكل ($cuesCount)"),
                Pair("male", "👨 ذكوري"),
                Pair("female", "👩 أنثوي"),
                Pair("child", "🧒 طفولي"),
                Pair("narrator", "🎙️ راوي")
            )

            filters.forEach { (genderKey, label) ->
                val isSelected = selectedGender == genderKey
                Surface(
                    shape = RoundedCornerShape(10.dp),
                    color = if (isSelected) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.45f),
                    border = BorderStroke(
                        0.8.dp,
                        if (isSelected) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.5f)
                    ),
                    modifier = Modifier
                        .clickable { onSelectGender(genderKey) }
                        .testTag("gender_filter_${genderKey ?: "all"}")
                ) {
                    Text(
                        text = label,
                        fontSize = 11.sp,
                        fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal,
                        color = if (isSelected) Color.White else MaterialTheme.colorScheme.onSurface,
                        modifier = Modifier.padding(horizontal = 10.dp, vertical = 5.dp)
                    )
                }
            }
        }
    }
}

/**
 * Individual Card presenting a single `LocalizedDubbingCue`
 */
@Composable
fun LocalizedDubbingCueCard(
    cue: LocalizedDubbingCue,
    index: Int,
    isPlaying: Boolean,
    onPlay: () -> Unit,
    onStop: () -> Unit,
    onSynthesize: () -> Unit,
    onEdit: () -> Unit,
    onApplyToStudio: () -> Unit,
    onCopyText: () -> Unit
) {
    val genderColor = when (cue.characterGender.lowercase()) {
        "female", "woman", "girl" -> Color(0xFFEC4899)
        "child", "kid" -> Color(0xFFF59E0B)
        "narrator" -> Color(0xFF10B981)
        else -> Color(0xFF6366F1)
    }

    val genderIcon: ImageVector = when (cue.characterGender.lowercase()) {
        "female", "woman", "girl" -> Icons.Default.Face
        "child", "kid" -> Icons.Default.Face
        "narrator" -> Icons.Default.RecordVoiceOver
        else -> Icons.Default.Person
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .testTag("localized_cue_card_${cue.id}"),
        shape = RoundedCornerShape(16.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (isPlaying)
                MaterialTheme.colorScheme.primary.copy(alpha = 0.10f)
            else
                MaterialTheme.colorScheme.surface
        ),
        border = BorderStroke(
            if (isPlaying) 1.5.dp else 1.dp,
            if (isPlaying) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.45f)
        )
    ) {
        Column(
            modifier = Modifier.padding(14.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp)
        ) {
            // Header Row: Index, Time range, Speaker Badge, Gender Icon
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    // Index badge
                    Surface(
                        shape = CircleShape,
                        color = MaterialTheme.colorScheme.primary.copy(alpha = 0.15f),
                        modifier = Modifier.size(24.dp)
                    ) {
                        Box(contentAlignment = Alignment.Center) {
                            Text(
                                text = "$index",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                color = MaterialTheme.colorScheme.primary
                            )
                        }
                    }

                    // Speaker Name and Gender
                    Surface(
                        shape = RoundedCornerShape(8.dp),
                        color = genderColor.copy(alpha = 0.15f)
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(4.dp),
                            modifier = Modifier.padding(horizontal = 8.dp, vertical = 3.dp)
                        ) {
                            Icon(
                                imageVector = genderIcon,
                                contentDescription = null,
                                tint = genderColor,
                                modifier = Modifier.size(13.dp)
                            )
                            Text(
                                text = cue.characterSpeakerName,
                                fontSize = 11.5.sp,
                                fontWeight = FontWeight.Bold,
                                color = genderColor
                            )
                        }
                    }
                }

                // Timing Pill
                Surface(
                    shape = RoundedCornerShape(8.dp),
                    color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f)
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(4.dp),
                        modifier = Modifier.padding(horizontal = 7.dp, vertical = 3.dp)
                    ) {
                        Text(
                            text = "⏱️ ${cue.formattedTimeRange}",
                            fontSize = 11.sp,
                            fontWeight = FontWeight.SemiBold,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Text(
                            text = "(${String.format(Locale.getDefault(), "%.1f", cue.durationSeconds)}s)",
                            fontSize = 10.sp,
                            color = MaterialTheme.colorScheme.outline
                        )
                    }
                }
            }

            // Visual Action & Scene Description
            if (cue.visualActionDescription.isNotBlank()) {
                Surface(
                    shape = RoundedCornerShape(10.dp),
                    color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(horizontal = 10.dp, vertical = 6.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(6.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.Movie,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(14.dp)
                        )
                        Text(
                            text = cue.visualActionDescription,
                            fontSize = 11.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            maxLines = 2,
                            overflow = TextOverflow.Ellipsis
                        )
                    }
                }
            }

            // Localized Dubbed Script (Arabic, prominent)
            Surface(
                shape = RoundedCornerShape(12.dp),
                color = MaterialTheme.colorScheme.primary.copy(alpha = 0.08f),
                border = BorderStroke(0.5.dp, MaterialTheme.colorScheme.primary.copy(alpha = 0.25f)),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(10.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                    Text(
                        text = "النص العربي المدبلج:",
                        fontSize = 10.sp,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = cue.localizedDubbedScript,
                        fontSize = 13.5.sp,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onSurface,
                        lineHeight = 20.sp
                    )
                }
            }

            // Original Dialogue (if present)
            if (cue.originalDialogue.isNotBlank()) {
                Text(
                    text = "الأصل: \"${cue.originalDialogue}\"",
                    fontSize = 11.sp,
                    color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.8f),
                    style = androidx.compose.ui.text.TextStyle(fontStyle = androidx.compose.ui.text.font.FontStyle.Italic),
                    modifier = Modifier.padding(horizontal = 4.dp)
                )
            }

            // Audio synthesis parameters: Tone, Pitch, Rate, Lip-sync Confidence
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(6.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                // Tone
                Surface(
                    shape = RoundedCornerShape(6.dp),
                    color = Color(0xFF6366F1).copy(alpha = 0.12f)
                ) {
                    Text(
                        text = "🎭 ${cue.emotionalTone}",
                        fontSize = 10.sp,
                        color = Color(0xFF818CF8),
                        fontWeight = FontWeight.Medium,
                        modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp)
                    )
                }

                // Confidence
                Surface(
                    shape = RoundedCornerShape(6.dp),
                    color = Color(0xFF10B981).copy(alpha = 0.12f)
                ) {
                    Text(
                        text = "مزامنة شفاه: ${(cue.lipSyncConfidence * 100).toInt()}%",
                        fontSize = 10.sp,
                        color = Color(0xFF34D399),
                        fontWeight = FontWeight.Medium,
                        modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp)
                    )
                }

                // Pitch & Rate
                Text(
                    text = "🎚️ ${cue.suggestedVoicePitch}x • ⚡ ${cue.suggestedSpeechRate}x",
                    fontSize = 10.sp,
                    color = MaterialTheme.colorScheme.outline
                )
            }

            // Playing Animated Waves
            if (isPlaying) {
                PlayingAudioWaveIndicator()
            }

            // Bottom Action Bar: Play/Stop, Synthesize, Edit, Copy, Apply to Studio
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                // Play / Stop button
                Button(
                    onClick = if (isPlaying) onStop else onPlay,
                    colors = ButtonDefaults.buttonColors(
                        containerColor = if (isPlaying) Color(0xFFEF4444) else Color(0xFF10B981)
                    ),
                    shape = RoundedCornerShape(10.dp),
                    modifier = Modifier
                        .height(38.dp)
                        .testTag("play_cue_button_${cue.id}")
                ) {
                    Icon(
                        imageVector = if (isPlaying) Icons.Default.Stop else Icons.Default.PlayArrow,
                        contentDescription = null,
                        modifier = Modifier.size(16.dp)
                    )
                    Spacer(Modifier.width(4.dp))
                    Text(
                        text = if (isPlaying) "إيقاف ⏹️" else "تشغيل المقطع ▶",
                        fontSize = 11.5.sp,
                        fontWeight = FontWeight.Bold
                    )
                }

                // Quick Action Icon Buttons
                Row(
                    horizontalArrangement = Arrangement.spacedBy(4.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    // Apply to Studio
                    IconButton(
                        onClick = onApplyToStudio,
                        modifier = Modifier
                            .size(34.dp)
                            .testTag("apply_cue_to_studio_${cue.id}")
                    ) {
                        Icon(
                            imageVector = Icons.Default.Videocam,
                            contentDescription = "استخدام بالاستوديو",
                            tint = Color(0xFF3B82F6),
                            modifier = Modifier.size(18.dp)
                        )
                    }

                    // Synthesize to file
                    IconButton(
                        onClick = onSynthesize,
                        modifier = Modifier
                            .size(34.dp)
                            .testTag("synthesize_cue_${cue.id}")
                    ) {
                        Icon(
                            imageVector = if (cue.generatedAudioPath != null) Icons.Default.CheckCircle else Icons.Default.Save,
                            contentDescription = "توليد ملف صوتي",
                            tint = if (cue.generatedAudioPath != null) Color(0xFF10B981) else MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(18.dp)
                        )
                    }

                    // Edit Script
                    IconButton(
                        onClick = onEdit,
                        modifier = Modifier
                            .size(34.dp)
                            .testTag("edit_cue_${cue.id}")
                    ) {
                        Icon(
                            imageVector = Icons.Default.Edit,
                            contentDescription = "تعديل النص",
                            tint = MaterialTheme.colorScheme.onSurfaceVariant,
                            modifier = Modifier.size(17.dp)
                        )
                    }

                    // Copy Text
                    IconButton(
                        onClick = onCopyText,
                        modifier = Modifier.size(34.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.ContentCopy,
                            contentDescription = "نسخ النص",
                            tint = MaterialTheme.colorScheme.onSurfaceVariant,
                            modifier = Modifier.size(17.dp)
                        )
                    }
                }
            }
        }
    }
}

/**
 * Animated Audio Equalizer Wave Bar Indicator while playing
 */
@Composable
fun PlayingAudioWaveIndicator() {
    val infiniteTransition = rememberInfiniteTransition(label = "wave_bars")

    val h1 by infiniteTransition.animateFloat(
        initialValue = 0.25f,
        targetValue = 0.95f,
        animationSpec = infiniteRepeatable(tween(400), RepeatMode.Reverse),
        label = "h1"
    )
    val h2 by infiniteTransition.animateFloat(
        initialValue = 0.85f,
        targetValue = 0.30f,
        animationSpec = infiniteRepeatable(tween(350), RepeatMode.Reverse),
        label = "h2"
    )
    val h3 by infiniteTransition.animateFloat(
        initialValue = 0.40f,
        targetValue = 1.0f,
        animationSpec = infiniteRepeatable(tween(500), RepeatMode.Reverse),
        label = "h3"
    )
    val h4 by infiniteTransition.animateFloat(
        initialValue = 0.90f,
        targetValue = 0.20f,
        animationSpec = infiniteRepeatable(tween(380), RepeatMode.Reverse),
        label = "h4"
    )
    val h5 by infiniteTransition.animateFloat(
        initialValue = 0.30f,
        targetValue = 0.80f,
        animationSpec = infiniteRepeatable(tween(420), RepeatMode.Reverse),
        label = "h5"
    )

    Surface(
        shape = RoundedCornerShape(10.dp),
        color = MaterialTheme.colorScheme.primary.copy(alpha = 0.12f),
        modifier = Modifier.fillMaxWidth()
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 12.dp, vertical = 6.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween
        ) {
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                Icon(
                    imageVector = Icons.Default.GraphicEq,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.primary,
                    modifier = Modifier.size(16.dp)
                )
                Text(
                    text = "جاري تشغيل مقطع الصوت الآن بنبرة الشخصية...",
                    fontSize = 11.sp,
                    color = MaterialTheme.colorScheme.primary,
                    fontWeight = FontWeight.Bold
                )
            }

            // 5 Waveform bars
            Row(
                horizontalArrangement = Arrangement.spacedBy(3.dp),
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.height(18.dp)
            ) {
                listOf(h1, h2, h3, h4, h5).forEach { fraction ->
                    Box(
                        modifier = Modifier
                            .width(3.dp)
                            .height((18 * fraction).dp.coerceAtLeast(3.dp))
                            .clip(RoundedCornerShape(1.5.dp))
                            .background(MaterialTheme.colorScheme.primary)
                    )
                }
            }
        }
    }
}

/**
 * Reusable metadata pill badge
 */
@Composable
fun CueMetadataPill(
    icon: ImageVector,
    text: String,
    backgroundColor: Color,
    contentColor: Color
) {
    Surface(
        shape = RoundedCornerShape(8.dp),
        color = backgroundColor
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(4.dp),
            modifier = Modifier.padding(horizontal = 7.dp, vertical = 3.dp)
        ) {
            Icon(icon, contentDescription = null, tint = contentColor, modifier = Modifier.size(11.dp))
            Text(text = text, color = contentColor, fontSize = 10.5.sp, fontWeight = FontWeight.Bold)
        }
    }
}

/**
 * Empty state card when no cues match the search or filter criteria
 */
@Composable
fun EmptyCuesStateCard(
    hasFilters: Boolean,
    onResetFilters: () -> Unit,
    onLoadSample: () -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 20.dp),
        shape = RoundedCornerShape(18.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f))
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(10.dp)
        ) {
            Icon(
                imageVector = Icons.Default.GraphicEq,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.primary.copy(alpha = 0.7f),
                modifier = Modifier.size(44.dp)
            )
            Text(
                text = if (hasFilters) "لا توجد مقاطع صوتية مطابقة للتصفية الحالية" else "لم يتم العثور على مقاطع LocalizedDubbingCue",
                fontWeight = FontWeight.Bold,
                fontSize = 14.sp,
                textAlign = TextAlign.Center
            )
            Text(
                text = if (hasFilters)
                    "جرب تغيير كلمة البحث أو تحديد شخصية أخرى لإظهار المقاطع."
                else
                    "يمكنك استخراج وتوليد توقيتات دبلجة ذكية متزامنة تلقائياً من الفيديو بالذكاء الاصطناعي.",
                fontSize = 11.5.sp,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                textAlign = TextAlign.Center
            )

            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                if (hasFilters) {
                    Button(onClick = onResetFilters) {
                        Text("إلغاء التصفية")
                    }
                } else {
                    Button(onClick = onLoadSample) {
                        Text("توليد توقيتات ذكية بالذكاء الاصطناعي ✨")
                    }
                }
            }
        }
    }
}
