package com.example.localization

object AppStrings {

    fun appTitle(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "فويس ماستر برو | VoiceMaster Pro"
        AppLanguage.ENGLISH -> "VoiceMaster Pro | AI Dubbing Studio"
        AppLanguage.SPANISH -> "VoiceMaster Pro | Estudio de Doblaje IA"
        AppLanguage.FRENCH -> "VoiceMaster Pro | Studio de Doublage IA"
        AppLanguage.GERMAN -> "VoiceMaster Pro | KI-Synchronstudio"
        AppLanguage.TURKISH -> "VoiceMaster Pro | AI Dublaj Stüdyosu"
        AppLanguage.RUSSIAN -> "VoiceMaster Pro | ИИ Студия дубляжа"
        AppLanguage.CHINESE -> "VoiceMaster Pro | AI 配音工作室"
        AppLanguage.JAPANESE -> "VoiceMaster Pro | AI 吹き替えスタジオ"
        AppLanguage.KOREAN -> "VoiceMaster Pro | AI 더빙 스튜디오"
        AppLanguage.ITALIAN -> "VoiceMaster Pro | Studio Doppiaggio IA"
        AppLanguage.PORTUGUESE -> "VoiceMaster Pro | Estúdio de Dublagem IA"
        AppLanguage.HINDI -> "VoiceMaster Pro | एआई डबिंग स्टूडियो"
        AppLanguage.INDONESIAN -> "VoiceMaster Pro | Studio Dubbing AI"
        AppLanguage.PERSIAN -> "ویس مستر پرو | VoiceMaster Pro"
        AppLanguage.URDU -> "وائس ماسٹر پرو | VoiceMaster Pro"
    }

    fun tabVideoDub(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "دبلجة AI"
        AppLanguage.ENGLISH -> "AI Dub"
        AppLanguage.SPANISH -> "Doblaje AI"
        AppLanguage.FRENCH -> "Doublage AI"
        AppLanguage.GERMAN -> "KI-Dub"
        AppLanguage.TURKISH -> "AI Dublaj"
        AppLanguage.RUSSIAN -> "ИИ Дубляж"
        AppLanguage.CHINESE -> "AI配音"
        AppLanguage.JAPANESE -> "AI吹替"
        AppLanguage.KOREAN -> "AI더빙"
        AppLanguage.ITALIAN -> "Doppiaggio AI"
        AppLanguage.PORTUGUESE -> "Dublagem AI"
        AppLanguage.HINDI -> "एआई डब"
        AppLanguage.INDONESIAN -> "Dubbing AI"
        AppLanguage.PERSIAN -> "دوبله AI"
        AppLanguage.URDU -> "ڈبنگ AI"
    }

    fun tabStudio(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "الاستوديو"
        AppLanguage.ENGLISH -> "Studio"
        AppLanguage.SPANISH -> "Estudio"
        AppLanguage.FRENCH -> "Studio"
        AppLanguage.GERMAN -> "Studio"
        AppLanguage.TURKISH -> "Stüdyo"
        AppLanguage.RUSSIAN -> "Студия"
        AppLanguage.CHINESE -> "录音室"
        AppLanguage.JAPANESE -> "スタジオ"
        AppLanguage.KOREAN -> "스튜디오"
        AppLanguage.ITALIAN -> "Studio"
        AppLanguage.PORTUGUESE -> "Estúdio"
        AppLanguage.HINDI -> "स्टूडियो"
        AppLanguage.INDONESIAN -> "Studio"
        AppLanguage.PERSIAN -> "استودیو"
        AppLanguage.URDU -> "اسٹوڈیو"
    }

    fun tabVoices(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "الأصوات"
        AppLanguage.ENGLISH -> "Voices"
        AppLanguage.SPANISH -> "Voces"
        AppLanguage.FRENCH -> "Voix"
        AppLanguage.GERMAN -> "Stimmen"
        AppLanguage.TURKISH -> "Sesler"
        AppLanguage.RUSSIAN -> "Голоса"
        AppLanguage.CHINESE -> "音色库"
        AppLanguage.JAPANESE -> "ボイス"
        AppLanguage.KOREAN -> "음성"
        AppLanguage.ITALIAN -> "Voci"
        AppLanguage.PORTUGUESE -> "Vozes"
        AppLanguage.HINDI -> "आवाज़ें"
        AppLanguage.INDONESIAN -> "Suara"
        AppLanguage.PERSIAN -> "صداها"
        AppLanguage.URDU -> "آوازیں"
    }

    fun tabProjects(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "المشاريع"
        AppLanguage.ENGLISH -> "Projects"
        AppLanguage.SPANISH -> "Proyectos"
        AppLanguage.FRENCH -> "Projets"
        AppLanguage.GERMAN -> "Projekte"
        AppLanguage.TURKISH -> "Projeler"
        AppLanguage.RUSSIAN -> "Проекты"
        AppLanguage.CHINESE -> "我的项目"
        AppLanguage.JAPANESE -> "プロジェクト"
        AppLanguage.KOREAN -> "프로젝트"
        AppLanguage.ITALIAN -> "Progetti"
        AppLanguage.PORTUGUESE -> "Projetos"
        AppLanguage.HINDI -> "परियोजनाएं"
        AppLanguage.INDONESIAN -> "Proyek"
        AppLanguage.PERSIAN -> "پروژه‌ها"
        AppLanguage.URDU -> "پروجیکٹس"
    }

    fun tabSettings(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "الإعدادات"
        AppLanguage.ENGLISH -> "Settings"
        AppLanguage.SPANISH -> "Ajustes"
        AppLanguage.FRENCH -> "Paramètres"
        AppLanguage.GERMAN -> "Einstellungen"
        AppLanguage.TURKISH -> "Ayarlar"
        AppLanguage.RUSSIAN -> "Настройки"
        AppLanguage.CHINESE -> "设置"
        AppLanguage.JAPANESE -> "設定"
        AppLanguage.KOREAN -> "설정"
        AppLanguage.ITALIAN -> "Impostazioni"
        AppLanguage.PORTUGUESE -> "Configurações"
        AppLanguage.HINDI -> "सेटिंग्स"
        AppLanguage.INDONESIAN -> "Pengaturan"
        AppLanguage.PERSIAN -> "تنظیمات"
        AppLanguage.URDU -> "سیٹنگز"
    }

    fun moreTools(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "المزيد ⚡"
        AppLanguage.ENGLISH -> "More ⚡"
        AppLanguage.SPANISH -> "Más ⚡"
        AppLanguage.FRENCH -> "Plus ⚡"
        AppLanguage.GERMAN -> "Mehr ⚡"
        AppLanguage.TURKISH -> "Daha ⚡"
        AppLanguage.RUSSIAN -> "Ещё ⚡"
        AppLanguage.CHINESE -> "更多工具 ⚡"
        AppLanguage.JAPANESE -> "その他 ⚡"
        AppLanguage.KOREAN -> "더보기 ⚡"
        AppLanguage.ITALIAN -> "Altro ⚡"
        AppLanguage.PORTUGUESE -> "Mais ⚡"
        AppLanguage.HINDI -> "अधिक ⚡"
        AppLanguage.INDONESIAN -> "Lainnya ⚡"
        AppLanguage.PERSIAN -> "بیشتر ⚡"
        AppLanguage.URDU -> "مزید ⚡"
    }

    fun step1(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "1️⃣ اختر الفيديو"
        AppLanguage.ENGLISH -> "1️⃣ Pick Video"
        AppLanguage.SPANISH -> "1️⃣ Elegir Video"
        AppLanguage.FRENCH -> "1️⃣ Choisir Vidéo"
        AppLanguage.GERMAN -> "1️⃣ Video wählen"
        AppLanguage.TURKISH -> "1️⃣ Video Seç"
        AppLanguage.RUSSIAN -> "1️⃣ Выбрать видео"
        AppLanguage.CHINESE -> "1️⃣ 选择视频"
        AppLanguage.JAPANESE -> "1️⃣ 動画を選択"
        AppLanguage.KOREAN -> "1️⃣ 비디오 선택"
        AppLanguage.ITALIAN -> "1️⃣ Scegli Video"
        AppLanguage.PORTUGUESE -> "1️⃣ Escolher Vídeo"
        AppLanguage.HINDI -> "1️⃣ वीडियो चुनें"
        AppLanguage.INDONESIAN -> "1️⃣ Pilih Video"
        AppLanguage.PERSIAN -> "1️⃣ انتخاب ویدیو"
        AppLanguage.URDU -> "1️⃣ ویڈیو منتخب کریں"
    }

    fun step2(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "2️⃣ حدد اللغة والصوت"
        AppLanguage.ENGLISH -> "2️⃣ Set Language & Voice"
        AppLanguage.SPANISH -> "2️⃣ Idioma y Voz"
        AppLanguage.FRENCH -> "2️⃣ Langue et Voix"
        AppLanguage.GERMAN -> "2️⃣ Sprache & Stimme"
        AppLanguage.TURKISH -> "2️⃣ Dil ve Ses"
        AppLanguage.RUSSIAN -> "2️⃣ Язык и Голос"
        AppLanguage.CHINESE -> "2️⃣ 选择语言与音色"
        AppLanguage.JAPANESE -> "2️⃣ 言語と音声を選択"
        AppLanguage.KOREAN -> "2️⃣ 언어 및 음성 설정"
        AppLanguage.ITALIAN -> "2️⃣ Lingua e Voce"
        AppLanguage.PORTUGUESE -> "2️⃣ Idioma e Voz"
        AppLanguage.HINDI -> "2️⃣ भाषा और आवाज़"
        AppLanguage.INDONESIAN -> "2️⃣ Bahasa & Suara"
        AppLanguage.PERSIAN -> "2️⃣ زبان و صدا"
        AppLanguage.URDU -> "2️⃣ زبان اور آواز"
    }

    fun step3(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "3️⃣ دبلجة ودمج فوري!"
        AppLanguage.ENGLISH -> "3️⃣ Instant Dub & Merge!"
        AppLanguage.SPANISH -> "3️⃣ ¡Doblaje y Fusión Instantánea!"
        AppLanguage.FRENCH -> "3️⃣ Doublage et Fusion Immédiats !"
        AppLanguage.GERMAN -> "3️⃣ Sofort Dubben & Mischen!"
        AppLanguage.TURKISH -> "3️⃣ Anında Dublaj ve Birleştir!"
        AppLanguage.RUSSIAN -> "3️⃣ Мгновенный дубляж и сведение!"
        AppLanguage.CHINESE -> "3️⃣ 一键配音与合成！"
        AppLanguage.JAPANESE -> "3️⃣ 即座に吹き替え＆結合！"
        AppLanguage.KOREAN -> "3️⃣ 원클릭 더빙 및 합성!"
        AppLanguage.ITALIAN -> "3️⃣ Doppia e Unisci Subito!"
        AppLanguage.PORTUGUESE -> "3️⃣ Dublar e Mesclar Instantaneamente!"
        AppLanguage.HINDI -> "3️⃣ तुरंत डब और मर्ज करें!"
        AppLanguage.INDONESIAN -> "3️⃣ Dubbing & Gabung Instan!"
        AppLanguage.PERSIAN -> "3️⃣ دوبله و ادغام فوری!"
        AppLanguage.URDU -> "3️⃣ فوری ڈبنگ اور انضمام!"
    }

    fun startDubbingNow(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "🚀 بدء الدبلجة والدمج التلقائي الآن"
        AppLanguage.ENGLISH -> "🚀 Start Auto Dubbing & Merging Now"
        AppLanguage.SPANISH -> "🚀 Iniciar Doblaje y Fusión Automática"
        AppLanguage.FRENCH -> "🚀 Lancer le Doublage et la Fusion Auto"
        AppLanguage.GERMAN -> "🚀 Automatische Synchronisation jetzt starten"
        AppLanguage.TURKISH -> "🚀 Otomatik Dublajı Başlat"
        AppLanguage.RUSSIAN -> "🚀 Запустить автодубляж и слияние"
        AppLanguage.CHINESE -> "🚀 立即开始全自动配音与合成"
        AppLanguage.JAPANESE -> "🚀 自動吹き替え＆結合を開始"
        AppLanguage.KOREAN -> "🚀 자동 더빙 및 비디오 합성 시작"
        AppLanguage.ITALIAN -> "🚀 Avvia Doppiaggio e Unione Automatica"
        AppLanguage.PORTUGUESE -> "🚀 Iniciar Dublagem e Mesclagem Automática"
        AppLanguage.HINDI -> "🚀 ऑटो डबिंग और मर्जिंग शुरू करें"
        AppLanguage.INDONESIAN -> "🚀 Mulai Dubbing & Gabung Otomatis Sekarang"
        AppLanguage.PERSIAN -> "🚀 شروع دوبله و ادغام خودکار"
        AppLanguage.URDU -> "🚀 خودکار ڈبنگ اور انضمام شروع کریں"
    }

    fun settingsTitle(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "⚙️ إعدادات التطبيق والدبلجة"
        AppLanguage.ENGLISH -> "⚙️ App & Dubbing Settings"
        AppLanguage.SPANISH -> "⚙️ Ajustes de la App y Doblaje"
        AppLanguage.FRENCH -> "⚙️ Paramètres de l'Application & Doublage"
        AppLanguage.GERMAN -> "⚙️ App- & Synchronisations-Einstellungen"
        AppLanguage.TURKISH -> "⚙️ Uygulama ve Dublaj Ayarları"
        AppLanguage.RUSSIAN -> "⚙️ Настройки приложения и дубляжа"
        AppLanguage.CHINESE -> "⚙️ 应用与配音设置"
        AppLanguage.JAPANESE -> "⚙️ アプリと吹き替えの設定"
        AppLanguage.KOREAN -> "⚙️ 앱 및 더빙 설정"
        AppLanguage.ITALIAN -> "⚙️ Impostazioni App e Doppiaggio"
        AppLanguage.PORTUGUESE -> "⚙️ Configurações do App e Dublagem"
        AppLanguage.HINDI -> "⚙️ ऐप और डबिंग सेटिंग्स"
        AppLanguage.INDONESIAN -> "⚙️ Pengaturan Aplikasi & Dubbing"
        AppLanguage.PERSIAN -> "⚙️ تنظیمات برنامه و دوبله"
        AppLanguage.URDU -> "⚙️ ایپ اور ڈبنگ ترتیبات"
    }

    fun languageSection(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "🌐 لغة الواجهة والترجمة"
        AppLanguage.ENGLISH -> "🌐 Interface Language & Localization"
        AppLanguage.SPANISH -> "🌐 Idioma de Interfaz y Localización"
        AppLanguage.FRENCH -> "🌐 Langue de l'Interface & Localisation"
        AppLanguage.GERMAN -> "🌐 Sprache & Lokalisierung"
        AppLanguage.TURKISH -> "🌐 Arayüz Dili ve Yerelleştirme"
        AppLanguage.RUSSIAN -> "🌐 Язык интерфейса и локализация"
        AppLanguage.CHINESE -> "🌐 界面语言与本地化"
        AppLanguage.JAPANESE -> "🌐 インターフェース言語"
        AppLanguage.KOREAN -> "🌐 인터페이스 언어 및 지역화"
        AppLanguage.ITALIAN -> "🌐 Lingua dell'Interfaccia"
        AppLanguage.PORTUGUESE -> "🌐 Idioma da Interface"
        AppLanguage.HINDI -> "🌐 इंटरफ़ेस भाषा"
        AppLanguage.INDONESIAN -> "🌐 Bahasa Antarmuka"
        AppLanguage.PERSIAN -> "🌐 زبان رابط کاربری"
        AppLanguage.URDU -> "🌐 انٹرفیس کی زبان"
    }

    fun themeSection(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "🎨 المظهر والألوان"
        AppLanguage.ENGLISH -> "🎨 Theme & Appearance"
        AppLanguage.SPANISH -> "🎨 Tema y Apariencia"
        AppLanguage.FRENCH -> "🎨 Thème & Apparence"
        AppLanguage.GERMAN -> "🎨 Design & Farbschema"
        AppLanguage.TURKISH -> "🎨 Tema ve Görünüm"
        AppLanguage.RUSSIAN -> "🎨 Тема и оформление"
        AppLanguage.CHINESE -> "🎨 主题与外观"
        AppLanguage.JAPANESE -> "🎨 テーマと外観"
        AppLanguage.KOREAN -> "🎨 테마 및 화면 스타일"
        AppLanguage.ITALIAN -> "🎨 Tema e Aspetto"
        AppLanguage.PORTUGUESE -> "🎨 Tema e Aparência"
        AppLanguage.HINDI -> "🎨 थीम और रूप"
        AppLanguage.INDONESIAN -> "🎨 Tema & Tampilan"
        AppLanguage.PERSIAN -> "🎨 تم و ظاهر"
        AppLanguage.URDU -> "🎨 تھیم اور ظاہری شکل"
    }

    fun audioExportSection(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "🎬 إعدادات تصدير الفيديو والصوت"
        AppLanguage.ENGLISH -> "🎬 Video & Audio Export Settings"
        AppLanguage.SPANISH -> "🎬 Ajustes de Exportación de Video y Audio"
        AppLanguage.FRENCH -> "🎬 Paramètres d'Export Vidéo et Audio"
        AppLanguage.GERMAN -> "🎬 Video- & Audio-Exporteinstellungen"
        AppLanguage.TURKISH -> "🎬 Video ve Ses Dışa Aktarma Ayarları"
        AppLanguage.RUSSIAN -> "🎬 Экспорт видео и аудио"
        AppLanguage.CHINESE -> "🎬 视频与音频导出设置"
        AppLanguage.JAPANESE -> "🎬 動画・音声エクスポート設定"
        AppLanguage.KOREAN -> "🎬 비디오 & 오디오 내보내기 설정"
        AppLanguage.ITALIAN -> "🎬 Impostazioni Esportazione Video e Audio"
        AppLanguage.PORTUGUESE -> "🎬 Configurações de Exportação"
        AppLanguage.HINDI -> "🎬 वीडियो और ऑडियो निर्यात सेटिंग्स"
        AppLanguage.INDONESIAN -> "🎬 Pengaturan Ekspor Video & Audio"
        AppLanguage.PERSIAN -> "🎬 تنظیمات خروجی ویدیو و صدا"
        AppLanguage.URDU -> "🎬 ویڈیو اور آڈیو ایکسپورٹ سیٹنگز"
    }

    fun aiEnginesSection(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "🤖 محركات الذكاء الاصطناعي والأصوات"
        AppLanguage.ENGLISH -> "🤖 AI & Voice Generation Engines"
        AppLanguage.SPANISH -> "🤖 Motores de IA y Generación de Voz"
        AppLanguage.FRENCH -> "🤖 Moteurs d'IA et Génération Vocale"
        AppLanguage.GERMAN -> "🤖 KI- & Sprachengines"
        AppLanguage.TURKISH -> "🤖 Yapay Zeka ve Ses Motorları"
        AppLanguage.RUSSIAN -> "🤖 ИИ и голосовые движки"
        AppLanguage.CHINESE -> "🤖 AI 与语音合成引擎"
        AppLanguage.JAPANESE -> "🤖 AI・音声合成エンジン"
        AppLanguage.KOREAN -> "🤖 AI 및 음성 합성 엔진"
        AppLanguage.ITALIAN -> "🤖 Motori IA e Sintesi Vocale"
        AppLanguage.PORTUGUESE -> "🤖 Motores de IA e Voz"
        AppLanguage.HINDI -> "🤖 एआई और वॉयस इंजन"
        AppLanguage.INDONESIAN -> "🤖 Mesin AI & Sintesis Suara"
        AppLanguage.PERSIAN -> "🤖 موتورهای هوش مصنوعی و صدا"
        AppLanguage.URDU -> "🤖 اے آئی اور آواز انجن"
    }

    fun storageSection(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "💾 الذاكرة المؤقتة وإعادة الضبط"
        AppLanguage.ENGLISH -> "💾 Storage, Cache & Reset"
        AppLanguage.SPANISH -> "💾 Almacenamiento, Caché y Restablecer"
        AppLanguage.FRENCH -> "💾 Stockage, Cache et Réinitialisation"
        AppLanguage.GERMAN -> "💾 Speicher, Cache & Zurücksetzen"
        AppLanguage.TURKISH -> "💾 Depolama, Önbellek ve Sıfırlama"
        AppLanguage.RUSSIAN -> "💾 Память, кэш и сброс"
        AppLanguage.CHINESE -> "💾 存储、缓存与重置"
        AppLanguage.JAPANESE -> "💾 ストレージ・キャッシュとリセット"
        AppLanguage.KOREAN -> "💾 저장공간, 캐시 및 초기화"
        AppLanguage.ITALIAN -> "💾 Memoria, Cache e Ripristino"
        AppLanguage.PORTUGUESE -> "💾 Armazenamento, Cache e Redefinir"
        AppLanguage.HINDI -> "💾 संग्रहण, कैश और रीसेट"
        AppLanguage.INDONESIAN -> "💾 Penyimpanan, Cache & Reset"
        AppLanguage.PERSIAN -> "💾 حافظه، کش و بازنشانی"
        AppLanguage.URDU -> "💾 اسٹوریج، کیش اور ری سیٹ"
    }

    fun aboutSection(lang: AppLanguage): String = when (lang) {
        AppLanguage.ARABIC -> "ℹ️ حول التطبيق والميزات"
        AppLanguage.ENGLISH -> "ℹ️ About App & Features"
        AppLanguage.SPANISH -> "ℹ️ Acerca de la App"
        AppLanguage.FRENCH -> "ℹ️ À Propos de l'App"
        AppLanguage.GERMAN -> "ℹ️ Über diese App"
        AppLanguage.TURKISH -> "ℹ️ Uygulama Hakkında"
        AppLanguage.RUSSIAN -> "ℹ️ О приложении"
        AppLanguage.CHINESE -> "ℹ️ 关于应用"
        AppLanguage.JAPANESE -> "ℹ️ アプリについて"
        AppLanguage.KOREAN -> "ℹ️ 앱 정보"
        AppLanguage.ITALIAN -> "ℹ️ Informazioni sull'App"
        AppLanguage.PORTUGUESE -> "ℹ️ Sobre o Aplicativo"
        AppLanguage.HINDI -> "ℹ️ ऐप के बारे में"
        AppLanguage.INDONESIAN -> "ℹ️ Tentang Aplikasi"
        AppLanguage.PERSIAN -> "ℹ️ درباره برنامه"
        AppLanguage.URDU -> "ℹ️ ایپ کے بارے میں"
    }
}
